---
--- Generated by Luanalysis
--- Created by Ancxk.
--- DateTime: 2024/4/29 上午 9:36
---
redis.replicate_commands()

local rate_limit_key = KEYS[1]
local burst = ARGV[1]
local rate = ARGV[2]
local period = ARGV[3]
local cost = tonumber(ARGV[4])

local nums = redis.call("get", rate_limit_key)


